
[build]
  publish = "."
  command = "npm ci && node server.js & sleep 3 && echo 'Ready'"
  ignore = "false"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/splash*/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
